import type { Metadata } from "next";
import { Geist, Geist_Mono, Newsreader } from "next/font/google";
import { IntroOverlay } from "@/components/intro/intro-overlay";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Mirrors src/lib/intro-state.ts (shouldSkipIntro: hasSeenIntro || prefersReducedMotion).
// Runs before hydration so <html data-intro> is set before the first paint (AD-001).
// Session storage key kept in sync with src/components/intro/intro-overlay.tsx.
const INTRO_PRE_HYDRATION_SCRIPT = `(function(){try{var seen=sessionStorage.getItem("crontech:intro-seen")==="1";var reduced=window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches;document.documentElement.setAttribute("data-intro",(seen||reduced)?"skip":"show")}catch(e){document.documentElement.setAttribute("data-intro","skip")}})();`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${newsreader.variable} h-full antialiased`}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{ __html: INTRO_PRE_HYDRATION_SCRIPT }}
        />
        {/* Hidden by default (and without JS, since data-intro is never set) - never forces display:block, so it doesn't fight the overlay's own display:flex when shown. */}
        <style>{`html:not([data-intro="show"]) .intro-overlay{display:none}`}</style>
      </head>
      <body className="min-h-full flex flex-col">
        <IntroOverlay />
        {children}
      </body>
    </html>
  );
}
